let marcCountryCodes = [
    {id: '', text: ''},
    {id: 'aa', text: 'Albania'},
    {id: 'abc', text: 'Alberta'},
    {id: '-ac', text: 'Ashmore and Cartier Islands'},
    {id: 'aca', text: 'Australian Capital Territory'},
    {id: 'ae', text: 'Algeria'},
    {id: 'af', text: 'Afghanistan'},
    {id: 'ag', text: 'Argentina'},
    {id: '-ai', text: 'Anguilla'},
    {id: 'ai', text: 'Armenia (Republic)'},
    {id: '-air', text: 'Armenian S.S.R.'},
    {id: 'aj', text: 'Azerbaijan'},
    {id: '-ajr', text: 'Azerbaijan S.S.R.'},
    {id: 'aku', text: 'Alaska'},
    {id: 'alu', text: 'Alabama'},
    {id: 'am', text: 'Anguilla'},
    {id: 'an', text: 'Andorra'},
    {id: 'ao', text: 'Angola'},
    {id: 'aq', text: 'Antigua and Barbuda'},
    {id: 'aru', text: 'Arkansas'},
    {id: 'as', text: 'American Samoa'},
    {id: 'at', text: 'Australia'},
    {id: 'au', text: 'Austria'},
    {id: 'aw', text: 'Aruba'},
    {id: 'ay', text: 'Antarctica'},
    {id: 'azu', text: 'Arizona'},
    {id: 'ba', text: 'Bahrain'},
    {id: 'bb', text: 'Barbados'},
    {id: 'bcc', text: 'British Columbia'},
    {id: 'bd', text: 'Burundi'},
    {id: 'be', text: 'Belgium'},
    {id: 'bf', text: 'Bahamas'},
    {id: 'bg', text: 'Bangladesh'},
    {id: 'bh', text: 'Belize'},
    {id: 'bi', text: 'British Indian Ocean Territory'},
    {id: 'bl', text: 'Brazil'},
    {id: 'bm', text: 'Bermuda Islands'},
    {id: 'bn', text: 'Bosnia and Herzegovina'},
    {id: 'bo', text: 'Bolivia'},
    {id: 'bp', text: 'Solomon Islands'},
    {id: 'br', text: 'Burma'},
    {id: 'bs', text: 'Botswana'},
    {id: 'bt', text: 'Bhutan'},
    {id: 'bu', text: 'Bulgaria'},
    {id: 'bv', text: 'Bouvet Island'},
    {id: 'bw', text: 'Belarus'},
    {id: '-bwr', text: 'Byelorussian S.S.R.'},
    {id: 'bx', text: 'Brunei'},
    {id: 'ca', text: 'Caribbean Netherlands'},
    {id: 'cau', text: 'California'},
    {id: 'cb', text: 'Cambodia'},
    {id: 'cc', text: 'China'},
    {id: 'cd', text: 'Chad'},
    {id: 'ce', text: 'Sri Lanka'},
    {id: 'cf', text: 'Congo (Brazzaville)'},
    {id: 'cg', text: 'Congo (Democratic Republic)'},
    {id: 'ch', text: 'China (Republic : 1949- )'},
    {id: 'ci', text: 'Croatia'},
    {id: 'cj', text: 'Cayman Islands'},
    {id: 'ck', text: 'Colombia'},
    {id: 'cl', text: 'Chile'},
    {id: 'cm', text: 'Cameroon'},
    {id: '-cn', text: 'Canada'},
    {id: 'co', text: 'Curaçao'},
    {id: 'cou', text: 'Colorado'},
    {id: '-cp', text: 'Canton and Enderbury Islands'},
    {id: 'cq', text: 'Comoros'},
    {id: 'cr', text: 'Costa Rica'},
    {id: '-cs', text: 'Czechoslovakia'},
    {id: 'ctu', text: 'Connecticut'},
    {id: 'cu', text: 'Cuba'},
    {id: 'cv', text: 'Cabo Verde'},
    {id: 'cw', text: 'Cook Islands'},
    {id: 'cx', text: 'Central African Republic'},
    {id: 'cy', text: 'Cyprus'},
    {id: '-cz', text: 'Canal Zone'},
    {id: 'dcu', text: 'District of Columbia'},
    {id: 'deu', text: 'Delaware'},
    {id: 'dk', text: 'Denmark'},
    {id: 'dm', text: 'Benin'},
    {id: 'dq', text: 'Dominica'},
    {id: 'dr', text: 'Dominican Republic'},
    {id: 'ea', text: 'Eritrea'},
    {id: 'ec', text: 'Ecuador'},
    {id: 'eg', text: 'Equatorial Guinea'},
    {id: 'em', text: 'Timor-Leste'},
    {id: 'enk', text: 'England'},
    {id: 'er', text: 'Estonia'},
    {id: '-err', text: 'Estonia'},
    {id: 'es', text: 'El Salvador'},
    {id: 'et', text: 'Ethiopia'},
    {id: 'fa', text: 'Faroe Islands'},
    {id: 'fg', text: 'French Guiana'},
    {id: 'fi', text: 'Finland'},
    {id: 'fj', text: 'Fiji'},
    {id: 'fk', text: 'Falkland Islands'},
    {id: 'flu', text: 'Florida'},
    {id: 'fm', text: 'Micronesia (Federated States)'},
    {id: 'fp', text: 'French Polynesia'},
    {id: 'fr', text: 'France'},
    {id: 'fs', text: 'Terres australes et antarctiques françaises'},
    {id: 'ft', text: 'Djibouti'},
    {id: 'gau', text: 'Georgia'},
    {id: 'gb', text: 'Kiribati'},
    {id: 'gd', text: 'Grenada'},
    {id: '-ge', text: 'Germany (East)'},
    {id: 'gh', text: 'Ghana'},
    {id: 'gi', text: 'Gibraltar'},
    {id: 'gl', text: 'Greenland'},
    {id: 'gm', text: 'Gambia'},
    {id: '-gn', text: 'Gilbert and Ellice Islands'},
    {id: 'go', text: 'Gabon'},
    {id: 'gp', text: 'Guadeloupe'},
    {id: 'gr', text: 'Greece'},
    {id: 'gs', text: 'Georgia (Republic)'},
    {id: '-gsr', text: 'Georgian S.S.R.'},
    {id: 'gt', text: 'Guatemala'},
    {id: 'gu', text: 'Guam'},
    {id: 'gv', text: 'Guinea'},
    {id: 'gw', text: 'Germany'},
    {id: 'gy', text: 'Guyana'},
    {id: 'gz', text: 'Gaza Strip'},
    {id: 'hiu', text: 'Hawaii'},
    {id: '-hk', text: 'Hong Kong'},
    {id: 'hm', text: 'Heard and McDonald Islands'},
    {id: 'ho', text: 'Honduras'},
    {id: 'ht', text: 'Haiti'},
    {id: 'hu', text: 'Hungary'},
    {id: 'iau', text: 'Iowa'},
    {id: 'ic', text: 'Iceland'},
    {id: 'idu', text: 'Idaho'},
    {id: 'ie', text: 'Ireland'},
    {id: 'ii', text: 'India'},
    {id: 'ilu', text: 'Illinois'},
    {id: 'inu', text: 'Indiana'},
    {id: 'io', text: 'Indonesia'},
    {id: 'iq', text: 'Iraq'},
    {id: 'ir', text: 'Iran'},
    {id: 'is', text: 'Israel'},
    {id: 'it', text: 'Italy'},
    {id: '-iu', text: 'Israel-Syria Demilitarized Zones'},
    {id: 'iv', text: 'Côte d\'Ivoire'},
    {id: '-iw', text: 'Israel-Jordan Demilitarized Zones'},
    {id: 'iy', text: 'Iraq-Saudi Arabia Neutral Zone'},
    {id: 'ja', text: 'Japan'},
    {id: 'ji', text: 'Johnston Atoll'},
    {id: 'jm', text: 'Jamaica'},
    {id: '-jn', text: 'Jan Mayen'},
    {id: 'jo', text: 'Jordan'},
    {id: 'ke', text: 'Kenya'},
    {id: 'kg', text: 'Kyrgyzstan'},
    {id: '-kgr', text: 'Kirghiz S.S.R.'},
    {id: 'kn', text: 'Korea (North)'},
    {id: 'ko', text: 'Korea (South)'},
    {id: 'ksu', text: 'Kansas'},
    {id: 'ku', text: 'Kuwait'},
    {id: 'kv', text: 'Kosovo'},
    {id: 'kyu', text: 'Kentucky'},
    {id: 'kz', text: 'Kazakhstan'},
    {id: '-kzr', text: 'Kazakh S.S.R.'},
    {id: 'lau', text: 'Louisiana'},
    {id: 'lb', text: 'Liberia'},
    {id: 'le', text: 'Lebanon'},
    {id: 'lh', text: 'Liechtenstein'},
    {id: 'li', text: 'Lithuania'},
    {id: '-lir', text: 'Lithuania'},
    {id: '-ln', text: 'Central and Southern Line Islands'},
    {id: 'lo', text: 'Lesotho'},
    {id: 'ls', text: 'Laos'},
    {id: 'lu', text: 'Luxembourg'},
    {id: 'lv', text: 'Latvia'},
    {id: '-lvr', text: 'Latvia'},
    {id: 'ly', text: 'Libya'},
    {id: 'mau', text: 'Massachusetts'},
    {id: 'mbc', text: 'Manitoba'},
    {id: 'mc', text: 'Monaco'},
    {id: 'mdu', text: 'Maryland'},
    {id: 'meu', text: 'Maine'},
    {id: 'mf', text: 'Mauritius'},
    {id: 'mg', text: 'Madagascar'},
    {id: '-mh', text: 'Macao'},
    {id: 'miu', text: 'Michigan'},
    {id: 'mj', text: 'Montserrat'},
    {id: 'mk', text: 'Oman'},
    {id: 'ml', text: 'Mali'},
    {id: 'mm', text: 'Malta'},
    {id: 'mnu', text: 'Minnesota'},
    {id: 'mo', text: 'Montenegro'},
    {id: 'mou', text: 'Missouri'},
    {id: 'mp', text: 'Mongolia'},
    {id: 'mq', text: 'Martinique'},
    {id: 'mr', text: 'Morocco'},
    {id: 'msu', text: 'Mississippi'},
    {id: 'mtu', text: 'Montana'},
    {id: 'mu', text: 'Mauritania'},
    {id: 'mv', text: 'Moldova'},
    {id: '-mvr', text: 'Moldavian S.S.R.'},
    {id: 'mw', text: 'Malawi'},
    {id: 'mx', text: 'Mexico'},
    {id: 'my', text: 'Malaysia'},
    {id: 'mz', text: 'Mozambique'},
    {id: '-na', text: 'Netherlands Antilles'},
    {id: 'nbu', text: 'Nebraska'},
    {id: 'ncu', text: 'North Carolina'},
    {id: 'ndu', text: 'North Dakota'},
    {id: 'ne', text: 'Netherlands'},
    {id: 'nfc', text: 'Newfoundland and Labrador'},
    {id: 'ng', text: 'Niger'},
    {id: 'nhu', text: 'New Hampshire'},
    {id: 'nik', text: 'Northern Ireland'},
    {id: 'nju', text: 'New Jersey'},
    {id: 'nkc', text: 'New Brunswick'},
    {id: 'nl', text: 'New Caledonia'},
    {id: '-nm', text: 'Northern Mariana Islands'},
    {id: 'nmu', text: 'New Mexico'},
    {id: 'nn', text: 'Vanuatu'},
    {id: 'no', text: 'Norway'},
    {id: 'np', text: 'Nepal'},
    {id: 'nq', text: 'Nicaragua'},
    {id: 'nr', text: 'Nigeria'},
    {id: 'nsc', text: 'Nova Scotia'},
    {id: 'ntc', text: 'Northwest Territories'},
    {id: 'nu', text: 'Nauru'},
    {id: 'nuc', text: 'Nunavut'},
    {id: 'nvu', text: 'Nevada'},
    {id: 'nw', text: 'Northern Mariana Islands'},
    {id: 'nx', text: 'Norfolk Island'},
    {id: 'nyu', text: 'New York (State)'},
    {id: 'nz', text: 'New Zealand'},
    {id: 'ohu', text: 'Ohio'},
    {id: 'oku', text: 'Oklahoma'},
    {id: 'onc', text: 'Ontario'},
    {id: 'oru', text: 'Oregon'},
    {id: 'ot', text: 'Mayotte'},
    {id: 'pau', text: 'Pennsylvania'},
    {id: 'pc', text: 'Pitcairn Island'},
    {id: 'pe', text: 'Peru'},
    {id: 'pf', text: 'Paracel Islands'},
    {id: 'pg', text: 'Guinea-Bissau'},
    {id: 'ph', text: 'Philippines'},
    {id: 'pic', text: 'Prince Edward Island'},
    {id: 'pk', text: 'Pakistan'},
    {id: 'pl', text: 'Poland'},
    {id: 'pn', text: 'Panama'},
    {id: 'po', text: 'Portugal'},
    {id: 'pp', text: 'Papua New Guinea'},
    {id: 'pr', text: 'Puerto Rico'},
    {id: '-pt', text: 'Portuguese Timor'},
    {id: 'pw', text: 'Palau'},
    {id: 'py', text: 'Paraguay'},
    {id: 'qa', text: 'Qatar'},
    {id: 'qea', text: 'Queensland'},
    {id: 'quc', text: 'Québec (Province)'},
    {id: 'rb', text: 'Serbia'},
    {id: 're', text: 'Réunion'},
    {id: 'rh', text: 'Zimbabwe'},
    {id: 'riu', text: 'Rhode Island'},
    {id: 'rm', text: 'Romania'},
    {id: 'ru', text: 'Russia (Federation)'},
    {id: '-rur', text: 'Russian S.F.S.R.'},
    {id: 'rw', text: 'Rwanda'},
    {id: '-ry', text: 'Ryukyu Islands, Southern'},
    {id: 'sa', text: 'South Africa'},
    {id: '-sb', text: 'Svalbard'},
    {id: 'sc', text: 'Saint-Barthélemy'},
    {id: 'scu', text: 'South Carolina'},
    {id: 'sd', text: 'South Sudan'},
    {id: 'sdu', text: 'South Dakota'},
    {id: 'se', text: 'Seychelles'},
    {id: 'sf', text: 'Sao Tome and Principe'},
    {id: 'sg', text: 'Senegal'},
    {id: 'sh', text: 'Spanish North Africa'},
    {id: 'si', text: 'Singapore'},
    {id: 'sj', text: 'Sudan'},
    {id: '-sk', text: 'Sikkim'},
    {id: 'sl', text: 'Sierra Leone'},
    {id: 'sm', text: 'San Marino'},
    {id: 'sn', text: 'Sint Maarten'},
    {id: 'snc', text: 'Saskatchewan'},
    {id: 'so', text: 'Somalia'},
    {id: 'sp', text: 'Spain'},
    {id: 'sq', text: 'Swaziland'},
    {id: 'sr', text: 'Surinam'},
    {id: 'ss', text: 'Western Sahara'},
    {id: 'st', text: 'Saint-Martin'},
    {id: 'stk', text: 'Scotland'},
    {id: 'su', text: 'Saudi Arabia'},
    {id: '-sv', text: 'Swan Islands'},
    {id: 'sw', text: 'Sweden'},
    {id: 'sx', text: 'Namibia'},
    {id: 'sy', text: 'Syria'},
    {id: 'sz', text: 'Switzerland'},
    {id: 'ta', text: 'Tajikistan'},
    {id: '-tar', text: 'Tajik S.S.R.'},
    {id: 'tc', text: 'Turks and Caicos Islands'},
    {id: 'tg', text: 'Togo'},
    {id: 'th', text: 'Thailand'},
    {id: 'ti', text: 'Tunisia'},
    {id: 'tk', text: 'Turkmenistan'},
    {id: '-tkr', text: 'Turkmen S.S.R.'},
    {id: 'tl', text: 'Tokelau'},
    {id: 'tma', text: 'Tasmania'},
    {id: 'tnu', text: 'Tennessee'},
    {id: 'to', text: 'Tonga'},
    {id: 'tr', text: 'Trinidad and Tobago'},
    {id: 'ts', text: 'United Arab Emirates'},
    {id: '-tt', text: 'Trust Territory of the Pacific Islands'},
    {id: 'tu', text: 'Turkey'},
    {id: 'tv', text: 'Tuvalu'},
    {id: 'txu', text: 'Texas'},
    {id: 'tz', text: 'Tanzania'},
    {id: 'ua', text: 'Egypt'},
    {id: 'uc', text: 'United States Misc. Caribbean Islands'},
    {id: 'ug', text: 'Uganda'},
    {id: '-ui', text: 'United Kingdom Misc. Islands'},
    {id: 'uik', text: 'United Kingdom Misc. Islands'},
    {id: '-uk', text: 'United Kingdom'},
    {id: 'un', text: 'Ukraine'},
    {id: '-unr', text: 'Ukraine'},
    {id: 'up', text: 'United States Misc. Pacific Islands'},
    {id: '-ur', text: 'Soviet Union'},
    {id: '-us', text: 'United States'},
    {id: 'utu', text: 'Utah'},
    {id: 'uv', text: 'Burkina Faso'},
    {id: 'uy', text: 'Uruguay'},
    {id: 'uz', text: 'Uzbekistan'},
    {id: '-uzr', text: 'Uzbek S.S.R.'},
    {id: 'vau', text: 'Virginia'},
    {id: 'vb', text: 'British Virgin Islands'},
    {id: 'vc', text: 'Vatican City'},
    {id: 've', text: 'Venezuela'},
    {id: 'vi', text: 'Virgin Islands of the United States'},
    {id: 'vm', text: 'Vietnam'},
    {id: '-vn', text: 'Vietnam, North'},
    {id: 'vp', text: 'Various places'},
    {id: 'vra', text: 'Victoria'},
    {id: '-vs', text: 'Vietnam, South'},
    {id: 'vtu', text: 'Vermont'},
    {id: 'wau', text: 'Washington (State)'},
    {id: '-wb', text: 'West Berlin'},
    {id: 'wea', text: 'Western Australia'},
    {id: 'wf', text: 'Wallis and Futuna'},
    {id: 'wiu', text: 'Wisconsin'},
    {id: 'wj', text: 'West Bank of the Jordan River'},
    {id: 'wk', text: 'Wake Island'},
    {id: 'wlk', text: 'Wales'},
    {id: 'ws', text: 'Samoa'},
    {id: 'wvu', text: 'West Virginia'},
    {id: 'wyu', text: 'Wyoming'},
    {id: 'xa', text: 'Christmas Island (Indian Ocean)'},
    {id: 'xb', text: 'Cocos (Keeling) Islands'},
    {id: 'xc', text: 'Maldives'},
    {id: 'xd', text: 'Saint Kitts-Nevis'},
    {id: 'xe', text: 'Marshall Islands'},
    {id: 'xf', text: 'Midway Islands'},
    {id: 'xga', text: 'Coral Sea Islands Territory'},
    {id: 'xh', text: 'Niue'},
    {id: '-xi', text: 'Saint Kitts-Nevis-Anguilla'},
    {id: 'xj', text: 'Saint Helena'},
    {id: 'xk', text: 'Saint Lucia'},
    {id: 'xl', text: 'Saint Pierre and Miquelon'},
    {id: 'xm', text: 'Saint Vincent and the Grenadines'},
    {id: 'xn', text: 'Macedonia'},
    {id: 'xna', text: 'New South Wales'},
    {id: 'xo', text: 'Slovakia'},
    {id: 'xoa', text: 'Northern Territory'},
    {id: 'xp', text: 'Spratly Island'},
    {id: 'xr', text: 'Czech Republic'},
    {id: 'xra', text: 'South Australia'},
    {id: 'xs', text: 'South Georgia and the South Sandwich Islands'},
    {id: 'xv', text: 'Slovenia'},
    {id: 'xx', text: 'No place, unknown, or undetermined'},
    {id: 'xxc', text: 'Canada'},
    {id: 'xxk', text: 'United Kingdom'},
    {id: '-xxr', text: 'Soviet Union'},
    {id: 'xxu', text: 'United States'},
    {id: 'ye', text: 'Yemen'},
    {id: 'ykc', text: 'Yukon Territory'},
    {id: '-ys', text: 'Yemen (People\'s Democratic Republic)'},
    {id: '-yu', text: 'Serbia and Montenegro'},
    {id: 'za', text: 'Zambia'}
];
