let marclanguageCodes = [
    {id: '', text: ''},
    {id: 'aar', text: 'Afar'},
    {id: 'abk', text: 'Abkhaz'},
    {id: 'ace', text: 'Achinese'},
    {id: 'ach', text: 'Acoli'},
    {id: 'ada', text: 'Adangme'},
    {id: 'ady', text: 'Adygei'},
    {id: 'afa', text: 'Afroasiatic (Other)'},
    {id: 'afh', text: 'Afrihili (Artificial language)'},
    {id: 'afr', text: 'Afrikaans'},
    {id: 'ain', text: 'Ainu'},
    {id: '-ajm', text: 'Aljamía'},
    {id: 'aka', text: 'Akan'},
    {id: 'akk', text: 'Akkadian'},
    {id: 'alb', text: 'Albanian'},
    {id: 'ale', text: 'Aleut'},
    {id: 'alg', text: 'Algonquian (Other)'},
    {id: 'alt', text: 'Altai'},
    {id: 'amh', text: 'Amharic'},
    {id: 'ang', text: 'English, Old (ca. 450-1100)'},
    {id: 'anp', text: 'Angika'},
    {id: 'apa', text: 'Apache languages'},
    {id: 'ara', text: 'Arabic'},
    {id: 'arc', text: 'Aramaic'},
    {id: 'arg', text: 'Aragonese'},
    {id: 'arm', text: 'Armenian'},
    {id: 'arn', text: 'Mapuche'},
    {id: 'arp', text: 'Arapaho'},
    {id: 'art', text: 'Artificial (Other)'},
    {id: 'arw', text: 'Arawak'},
    {id: 'asm', text: 'Assamese'},
    {id: 'ast', text: 'Bable'},
    {id: 'ath', text: 'Athapascan (Other)'},
    {id: 'aus', text: 'Australian languages'},
    {id: 'ava', text: 'Avaric'},
    {id: 'ave', text: 'Avestan'},
    {id: 'awa', text: 'Awadhi'},
    {id: 'aym', text: 'Aymara'},
    {id: 'aze', text: 'Azerbaijani'},
    {id: 'bad', text: 'Banda languages'},
    {id: 'bai', text: 'Bamileke languages'},
    {id: 'bak', text: 'Bashkir'},
    {id: 'bal', text: 'Baluchi'},
    {id: 'bam', text: 'Bambara'},
    {id: 'ban', text: 'Balinese'},
    {id: 'baq', text: 'Basque'},
    {id: 'bas', text: 'Basa'},
    {id: 'bat', text: 'Baltic (Other)'},
    {id: 'bej', text: 'Beja'},
    {id: 'bel', text: 'Belarusian'},
    {id: 'bem', text: 'Bemba'},
    {id: 'ben', text: 'Bengali'},
    {id: 'ber', text: 'Berber (Other)'},
    {id: 'bho', text: 'Bhojpuri'},
    {id: 'bih', text: 'Bihari (Other)'},
    {id: 'bik', text: 'Bikol'},
    {id: 'bin', text: 'Edo'},
    {id: 'bis', text: 'Bislama'},
    {id: 'bla', text: 'Siksika'},
    {id: 'bnt', text: 'Bantu (Other)'},
    {id: 'bos', text: 'Bosnian'},
    {id: 'bra', text: 'Braj'},
    {id: 'bre', text: 'Breton'},
    {id: 'btk', text: 'Batak'},
    {id: 'bua', text: 'Buriat'},
    {id: 'bug', text: 'Bugis'},
    {id: 'bul', text: 'Bulgarian'},
    {id: 'bur', text: 'Burmese'},
    {id: 'byn', text: 'Bilin'},
    {id: 'cad', text: 'Caddo'},
    {id: 'cai', text: 'Central American Indian (Other)'},
    {id: '-cam', text: 'Khmer'},
    {id: 'car', text: 'Carib'},
    {id: 'cat', text: 'Catalan'},
    {id: 'cau', text: 'Caucasian (Other)'},
    {id: 'ceb', text: 'Cebuano'},
    {id: 'cel', text: 'Celtic (Other)'},
    {id: 'cha', text: 'Chamorro'},
    {id: 'chb', text: 'Chibcha'},
    {id: 'che', text: 'Chechen'},
    {id: 'chg', text: 'Chagatai'},
    {id: 'chi', text: 'Chinese'},
    {id: 'chk', text: 'Chuukese'},
    {id: 'chm', text: 'Mari'},
    {id: 'chn', text: 'Chinook jargon'},
    {id: 'cho', text: 'Choctaw'},
    {id: 'chp', text: 'Chipewyan'},
    {id: 'chr', text: 'Cherokee'},
    {id: 'chu', text: 'Church Slavic'},
    {id: 'chv', text: 'Chuvash'},
    {id: 'chy', text: 'Cheyenne'},
    {id: 'cmc', text: 'Chamic languages'},
    {id: 'cop', text: 'Coptic'},
    {id: 'cor', text: 'Cornish'},
    {id: 'cos', text: 'Corsican'},
    {id: 'cpe', text: 'Creoles and Pidgins, English-based (Other)'},
    {id: 'cpf', text: 'Creoles and Pidgins, French-based (Other)'},
    {id: 'cpp', text: 'Creoles and Pidgins, Portuguese-based (Other)'},
    {id: 'cre', text: 'Cree'},
    {id: 'crh', text: 'Crimean Tatar'},
    {id: 'crp', text: 'Creoles and Pidgins (Other)'},
    {id: 'csb', text: 'Kashubian'},
    {id: 'cus', text: 'Cushitic (Other)'},
    {id: 'cze', text: 'Czech'},
    {id: 'dak', text: 'Dakota'},
    {id: 'dan', text: 'Danish'},
    {id: 'dar', text: 'Dargwa'},
    {id: 'day', text: 'Dayak'},
    {id: 'del', text: 'Delaware'},
    {id: 'den', text: 'Slavey'},
    {id: 'dgr', text: 'Dogrib'},
    {id: 'din', text: 'Dinka'},
    {id: 'div', text: 'Divehi'},
    {id: 'doi', text: 'Dogri'},
    {id: 'dra', text: 'Dravidian (Other)'},
    {id: 'dsb', text: 'Lower Sorbian'},
    {id: 'dua', text: 'Duala'},
    {id: 'dum', text: 'Dutch, Middle (ca. 1050-1350)'},
    {id: 'dut', text: 'Dutch'},
    {id: 'dyu', text: 'Dyula'},
    {id: 'dzo', text: 'Dzongkha'},
    {id: 'efi', text: 'Efik'},
    {id: 'egy', text: 'Egyptian'},
    {id: 'eka', text: 'Ekajuk'},
    {id: 'elx', text: 'Elamite'},
    {id: 'eng', text: 'English'},
    {id: 'enm', text: 'English, Middle (1100-1500)'},
    {id: 'epo', text: 'Esperanto'},
    {id: '-esk', text: 'Eskimo languages'},
    {id: '-esp', text: 'Esperanto'},
    {id: 'est', text: 'Estonian'},
    {id: '-eth', text: 'Ethiopic'},
    {id: 'ewe', text: 'Ewe'},
    {id: 'ewo', text: 'Ewondo'},
    {id: 'fan', text: 'Fang'},
    {id: 'fao', text: 'Faroese'},
    {id: '-far', text: 'Faroese'},
    {id: 'fat', text: 'Fanti'},
    {id: 'fij', text: 'Fijian'},
    {id: 'fil', text: 'Filipino'},
    {id: 'fin', text: 'Finnish'},
    {id: 'fiu', text: 'Finno-Ugrian (Other)'},
    {id: 'fon', text: 'Fon'},
    {id: 'fre', text: 'French'},
    {id: '-fri', text: 'Frisian'},
    {id: 'frm', text: 'French, Middle (ca. 1300-1600)'},
    {id: 'fro', text: 'French, Old (ca. 842-1300)'},
    {id: 'frr', text: 'North Frisian'},
    {id: 'frs', text: 'East Frisian'},
    {id: 'fry', text: 'Frisian'},
    {id: 'ful', text: 'Fula'},
    {id: 'fur', text: 'Friulian'},
    {id: 'gaa', text: 'Gã'},
    {id: '-gae', text: 'Scottish Gaelix'},
    {id: '-gag', text: 'Galician'},
    {id: '-gal', text: 'Oromo'},
    {id: 'gay', text: 'Gayo'},
    {id: 'gba', text: 'Gbaya'},
    {id: 'gem', text: 'Germanic (Other)'},
    {id: 'geo', text: 'Georgian'},
    {id: 'ger', text: 'German'},
    {id: 'gez', text: 'Ethiopic'},
    {id: 'gil', text: 'Gilbertese'},
    {id: 'gla', text: 'Scottish Gaelic'},
    {id: 'gle', text: 'Irish'},
    {id: 'glg', text: 'Galician'},
    {id: 'glv', text: 'Manx'},
    {id: 'gmh', text: 'German, Middle High (ca. 1050-1500)'},
    {id: 'goh', text: 'German, Old High (ca. 750-1050)'},
    {id: 'gon', text: 'Gondi'},
    {id: 'gor', text: 'Gorontalo'},
    {id: 'got', text: 'Gothic'},
    {id: 'grb', text: 'Grebo'},
    {id: 'grc', text: 'Greek, Ancient (to 1453)'},
    {id: 'gre', text: 'Greek, Modern (1453-)'},
    {id: 'grn', text: 'Guarani'},
    {id: 'gsw', text: 'Swiss German'},
    {id: '-gua', text: 'Guarani'},
    {id: 'guj', text: 'Gujarati'},
    {id: 'gwi', text: 'Gwich\'in'},
    {id: 'hai', text: 'Haida'},
    {id: 'hat', text: 'Haitian French Creole'},
    {id: 'hau', text: 'Hausa'},
    {id: 'haw', text: 'Hawaiian'},
    {id: 'heb', text: 'Hebrew'},
    {id: 'her', text: 'Herero'},
    {id: 'hil', text: 'Hiligaynon'},
    {id: 'him', text: 'Western Pahari languages'},
    {id: 'hin', text: 'Hindi'},
    {id: 'hit', text: 'Hittite'},
    {id: 'hmn', text: 'Hmong'},
    {id: 'hmo', text: 'Hiri Motu'},
    {id: 'hrv', text: 'Croatian'},
    {id: 'hsb', text: 'Upper Sorbian'},
    {id: 'hun', text: 'Hungarian'},
    {id: 'hup', text: 'Hupa'},
    {id: 'iba', text: 'Iban'},
    {id: 'ibo', text: 'Igbo'},
    {id: 'ice', text: 'Icelandic'},
    {id: 'ido', text: 'Ido'},
    {id: 'iii', text: 'Sichuan Yi'},
    {id: 'ijo', text: 'Ijo'},
    {id: 'iku', text: 'Inuktitut'},
    {id: 'ile', text: 'Interlingue'},
    {id: 'ilo', text: 'Iloko'},
    {id: 'ina', text: 'Interlingua (International Auxiliary Language Association)'},
    {id: 'inc', text: 'Indic (Other)'},
    {id: 'ind', text: 'Indonesian'},
    {id: 'ine', text: 'Indo-European (Other)'},
    {id: 'inh', text: 'Ingush'},
    {id: '-int', text: 'Interlingua (International Auxiliary Language Association)'},
    {id: 'ipk', text: 'Inupiaq'},
    {id: 'ira', text: 'Iranian (Other)'},
    {id: '-iri', text: 'Irish'},
    {id: 'iro', text: 'Iroquoian (Other)'},
    {id: 'ita', text: 'Italian'},
    {id: 'jav', text: 'Javanese'},
    {id: 'jbo', text: 'Lojban (Artificial language)'},
    {id: 'jpn', text: 'Japanese'},
    {id: 'jpr', text: 'Judeo-Persian'},
    {id: 'jrb', text: 'Judeo-Arabic'},
    {id: 'kaa', text: 'Kara-Kalpak'},
    {id: 'kab', text: 'Kabyle'},
    {id: 'kac', text: 'Kachin'},
    {id: 'kal', text: 'Kalâtdlisut'},
    {id: 'kam', text: 'Kamba'},
    {id: 'kan', text: 'Kannada'},
    {id: 'kar', text: 'Karen languages'},
    {id: 'kas', text: 'Kashmiri'},
    {id: 'kau', text: 'Kanuri'},
    {id: 'kaw', text: 'Kawi'},
    {id: 'kaz', text: 'Kazakh'},
    {id: 'kbd', text: 'Kabardian'},
    {id: 'kha', text: 'Khasi'},
    {id: 'khi', text: 'Khoisan (Other)'},
    {id: 'khm', text: 'Khmer'},
    {id: 'kho', text: 'Khotanese'},
    {id: 'kik', text: 'Kikuyu'},
    {id: 'kin', text: 'Kinyarwanda'},
    {id: 'kir', text: 'Kyrgyz'},
    {id: 'kmb', text: 'Kimbundu'},
    {id: 'kok', text: 'Konkani'},
    {id: 'kom', text: 'Komi'},
    {id: 'kon', text: 'Kongo'},
    {id: 'kor', text: 'Korean'},
    {id: 'kos', text: 'Kosraean'},
    {id: 'kpe', text: 'Kpelle'},
    {id: 'krc', text: 'Karachay-Balkar'},
    {id: 'krl', text: 'Karelian'},
    {id: 'kro', text: 'Kru (Other)'},
    {id: 'kru', text: 'Kurukh'},
    {id: 'kua', text: 'Kuanyama'},
    {id: 'kum', text: 'Kumyk'},
    {id: 'kur', text: 'Kurdish'},
    {id: '-kus', text: 'Kusaie'},
    {id: 'kut', text: 'Kootenai'},
    {id: 'lad', text: 'Ladino'},
    {id: 'lah', text: 'Lahndā'},
    {id: 'lam', text: 'Lamba (Zambia and Congo)'},
    {id: '-lan', text: 'Occitan (post 1500)'},
    {id: 'lao', text: 'Lao'},
    {id: '-lap', text: 'Sami'},
    {id: 'lat', text: 'Latin'},
    {id: 'lav', text: 'Latvian'},
    {id: 'lez', text: 'Lezgian'},
    {id: 'lim', text: 'Limburgish'},
    {id: 'lin', text: 'Lingala'},
    {id: 'lit', text: 'Lithuanian'},
    {id: 'lol', text: 'Mongo-Nkundu'},
    {id: 'loz', text: 'Lozi'},
    {id: 'ltz', text: 'Luxembourgish'},
    {id: 'lua', text: 'Luba-Lulua'},
    {id: 'lub', text: 'Luba-Katanga'},
    {id: 'lug', text: 'Ganda'},
    {id: 'lui', text: 'Luiseño'},
    {id: 'lun', text: 'Lunda'},
    {id: 'luo', text: 'Luo (Kenya and Tanzania)'},
    {id: 'lus', text: 'Lushai'},
    {id: 'mac', text: 'Macedonian'},
    {id: 'mad', text: 'Madurese'},
    {id: 'mag', text: 'Magahi'},
    {id: 'mah', text: 'Marshallese'},
    {id: 'mai', text: 'Maithili'},
    {id: 'mak', text: 'Makasar'},
    {id: 'mal', text: 'Malayalam'},
    {id: 'man', text: 'Mandingo'},
    {id: 'mao', text: 'Maori'},
    {id: 'map', text: 'Austronesian (Other)'},
    {id: 'mar', text: 'Marathi'},
    {id: 'mas', text: 'Maasai'},
    {id: '-max', text: 'Manx'},
    {id: 'may', text: 'Malay'},
    {id: 'mdf', text: 'Moksha'},
    {id: 'mdr', text: 'Mandar'},
    {id: 'men', text: 'Mende'},
    {id: 'mga', text: 'Irish, Middle (ca. 1100-1550)'},
    {id: 'mic', text: 'Micmac'},
    {id: 'min', text: 'Minangkabau'},
    {id: 'mis', text: 'Miscellaneous languages'},
    {id: 'mkh', text: 'Mon-Khmer (Other)'},
    {id: '-mla', text: 'Malagasy'},
    {id: 'mlg', text: 'Malagasy'},
    {id: 'mlt', text: 'Maltese'},
    {id: 'mnc', text: 'Manchu'},
    {id: 'mni', text: 'Manipuri'},
    {id: 'mno', text: 'Manobo languages'},
    {id: 'moh', text: 'Mohawk'},
    {id: '-mol', text: 'Moldavian'},
    {id: 'mon', text: 'Mongolian'},
    {id: 'mos', text: 'Mooré'},
    {id: 'mul', text: 'Multiple languages'},
    {id: 'mun', text: 'Munda (Other)'},
    {id: 'mus', text: 'Creek'},
    {id: 'mwl', text: 'Mirandese'},
    {id: 'mwr', text: 'Marwari'},
    {id: 'myn', text: 'Mayan languages'},
    {id: 'myv', text: 'Erzya'},
    {id: 'nah', text: 'Nahuatl'},
    {id: 'nai', text: 'North American Indian (Other)'},
    {id: 'nap', text: 'Neapolitan Italian'},
    {id: 'nau', text: 'Nauru'},
    {id: 'nav', text: 'Navajo'},
    {id: 'nbl', text: 'Ndebele (South Africa)'},
    {id: 'nde', text: 'Ndebele (Zimbabwe)'},
    {id: 'ndo', text: 'Ndonga'},
    {id: 'nds', text: 'Low German'},
    {id: 'nep', text: 'Nepali'},
    {id: 'new', text: 'Newari'},
    {id: 'nia', text: 'Nias'},
    {id: 'nic', text: 'Niger-Kordofanian (Other)'},
    {id: 'niu', text: 'Niuean'},
    {id: 'nno', text: 'Norwegian (Nynorsk)'},
    {id: 'nob', text: 'Norwegian (Bokmål)'},
    {id: 'nog', text: 'Nogai'},
    {id: 'non', text: 'Old Norse'},
    {id: 'nor', text: 'Norwegian'},
    {id: 'nqo', text: 'N\'Ko'},
    {id: 'nso', text: 'Northern Sotho'},
    {id: 'nub', text: 'Nubian languages'},
    {id: 'nwc', text: 'Newari, Old'},
    {id: 'nya', text: 'Nyanja'},
    {id: 'nym', text: 'Nyamwezi'},
    {id: 'nyn', text: 'Nyankole'},
    {id: 'nyo', text: 'Nyoro'},
    {id: 'nzi', text: 'Nzima'},
    {id: 'oci', text: 'Occitan (post-1500)'},
    {id: 'oji', text: 'Ojibwa'},
    {id: 'ori', text: 'Oriya'},
    {id: 'orm', text: 'Oromo'},
    {id: 'osa', text: 'Osage'},
    {id: 'oss', text: 'Ossetic'},
    {id: 'ota', text: 'Turkish, Ottoman'},
    {id: 'oto', text: 'Otomian languages'},
    {id: 'paa', text: 'Papuan (Other)'},
    {id: 'pag', text: 'Pangasinan'},
    {id: 'pal', text: 'Pahlavi'},
    {id: 'pam', text: 'Pampanga'},
    {id: 'pan', text: 'Panjabi'},
    {id: 'pap', text: 'Papiamento'},
    {id: 'pau', text: 'Palauan'},
    {id: 'peo', text: 'Old Persian (ca. 600-400 B.C.)'},
    {id: 'per', text: 'Persian'},
    {id: 'phi', text: 'Philippine (Other)'},
    {id: 'phn', text: 'Phoenician'},
    {id: 'pli', text: 'Pali'},
    {id: 'pol', text: 'Polish'},
    {id: 'pon', text: 'Pohnpeian'},
    {id: 'por', text: 'Portuguese'},
    {id: 'pra', text: 'Prakrit languages'},
    {id: 'pro', text: 'Provençal (to 1500)'},
    {id: 'pus', text: 'Pushto'},
    {id: 'que', text: 'Quechua'},
    {id: 'raj', text: 'Rajasthani'},
    {id: 'rap', text: 'Rapanui'},
    {id: 'rar', text: 'Rarotongan'},
    {id: 'roa', text: 'Romance (Other)'},
    {id: 'roh', text: 'Raeto-Romance'},
    {id: 'rom', text: 'Romani'},
    {id: 'rum', text: 'Romanian'},
    {id: 'run', text: 'Rundi'},
    {id: 'rup', text: 'Aromanian'},
    {id: 'rus', text: 'Russian'},
    {id: 'sad', text: 'Sandawe'},
    {id: 'sag', text: 'Sango (Ubangi Creole)'},
    {id: 'sah', text: 'Yakut'},
    {id: 'sai', text: 'South American Indian (Other)'},
    {id: 'sal', text: 'Salishan languages'},
    {id: 'sam', text: 'Samaritan Aramaic'},
    {id: 'san', text: 'Sanskrit'},
    {id: '-sao', text: 'Samoan'},
    {id: 'sas', text: 'Sasak'},
    {id: 'sat', text: 'Santali'},
    {id: '-scc', text: 'Serbian'},
    {id: 'scn', text: 'Sicilian Italian'},
    {id: 'sco', text: 'Scots'},
    {id: '-scr', text: 'Croatian'},
    {id: 'sel', text: 'Selkup'},
    {id: 'sem', text: 'Semitic (Other)'},
    {id: 'sga', text: 'Irish, Old (to 1100)'},
    {id: 'sgn', text: 'Sign languages'},
    {id: 'shn', text: 'Shan'},
    {id: '-sho', text: 'Shona'},
    {id: 'sid', text: 'Sidamo'},
    {id: 'sin', text: 'Sinhalese'},
    {id: 'sio', text: 'Siouan (Other)'},
    {id: 'sit', text: 'Sino-Tibetan (Other)'},
    {id: 'sla', text: 'Slavic (Other)'},
    {id: 'slo', text: 'Slovak'},
    {id: 'slv', text: 'Slovenian'},
    {id: 'sma', text: 'Southern Sami'},
    {id: 'sme', text: 'Northern Sami'},
    {id: 'smi', text: 'Sami'},
    {id: 'smj', text: 'Lule Sami'},
    {id: 'smn', text: 'Inari Sami'},
    {id: 'smo', text: 'Samoan'},
    {id: 'sms', text: 'Skolt Sami'},
    {id: 'sna', text: 'Shona'},
    {id: 'snd', text: 'Sindhi'},
    {id: '-snh', text: 'Sinhalese'},
    {id: 'snk', text: 'Soninke'},
    {id: 'sog', text: 'Sogdian'},
    {id: 'som', text: 'Somali'},
    {id: 'son', text: 'Songhai'},
    {id: 'sot', text: 'Sotho'},
    {id: 'spa', text: 'Spanish'},
    {id: 'srd', text: 'Sardinian'},
    {id: 'srn', text: 'Sranan'},
    {id: 'srp', text: 'Serbian'},
    {id: 'srr', text: 'Serer'},
    {id: 'ssa', text: 'Nilo-Saharan (Other)'},
    {id: '-sso', text: 'Sotho'},
    {id: 'ssw', text: 'Swazi'},
    {id: 'suk', text: 'Sukuma'},
    {id: 'sun', text: 'Sundanese'},
    {id: 'sus', text: 'Susu'},
    {id: 'sux', text: 'Sumerian'},
    {id: 'swa', text: 'Swahili'},
    {id: 'swe', text: 'Swedish'},
    {id: '-swz', text: 'Swazi'},
    {id: 'syc', text: 'Syriac'},
    {id: 'syr', text: 'Syriac, Modern'},
    {id: '-tag', text: 'Tagalog'},
    {id: 'tah', text: 'Tahitian'},
    {id: 'tai', text: 'Tai (Other)'},
    {id: '-taj', text: 'Tajik'},
    {id: 'tam', text: 'Tamil'},
    {id: '-tar', text: 'Tatar'},
    {id: 'tat', text: 'Tatar'},
    {id: 'tel', text: 'Telugu'},
    {id: 'tem', text: 'Temne'},
    {id: 'ter', text: 'Terena'},
    {id: 'tet', text: 'Tetum'},
    {id: 'tgk', text: 'Tajik'},
    {id: 'tgl', text: 'Tagalog'},
    {id: 'tha', text: 'Thai'},
    {id: 'tib', text: 'Tibetan'},
    {id: 'tig', text: 'Tigré'},
    {id: 'tir', text: 'Tigrinya'},
    {id: 'tiv', text: 'Tiv'},
    {id: 'tkl', text: 'Tokelauan'},
    {id: 'tlh', text: 'Klingon (Artificial language)'},
    {id: 'tli', text: 'Tlingit'},
    {id: 'tmh', text: 'Tamashek'},
    {id: 'tog', text: 'Tonga (Nyasa)'},
    {id: 'ton', text: 'Tongan'},
    {id: 'tpi', text: 'Tok Pisin'},
    {id: '-tru', text: 'Truk'},
    {id: 'tsi', text: 'Tsimshian'},
    {id: 'tsn', text: 'Tswana'},
    {id: 'tso', text: 'Tsonga'},
    {id: '-tsw', text: 'Tswana'},
    {id: 'tuk', text: 'Turkmen'},
    {id: 'tum', text: 'Tumbuka'},
    {id: 'tup', text: 'Tupi languages'},
    {id: 'tur', text: 'Turkish'},
    {id: 'tut', text: 'Altaic (Other)'},
    {id: 'tvl', text: 'Tuvaluan'},
    {id: 'twi', text: 'Twi'},
    {id: 'tyv', text: 'Tuvinian'},
    {id: 'udm', text: 'Udmurt'},
    {id: 'uga', text: 'Ugaritic'},
    {id: 'uig', text: 'Uighur'},
    {id: 'ukr', text: 'Ukrainian'},
    {id: 'umb', text: 'Umbundu'},
    {id: 'und', text: 'Undetermined'},
    {id: 'urd', text: 'Urdu'},
    {id: 'uzb', text: 'Uzbek'},
    {id: 'vai', text: 'Vai'},
    {id: 'ven', text: 'Venda'},
    {id: 'vie', text: 'Vietnamese'},
    {id: 'vol', text: 'Volapük'},
    {id: 'vot', text: 'Votic'},
    {id: 'wak', text: 'Wakashan languages'},
    {id: 'wal', text: 'Wolayta'},
    {id: 'war', text: 'Waray'},
    {id: 'was', text: 'Washoe'},
    {id: 'wel', text: 'Welsh'},
    {id: 'wen', text: 'Sorbian (Other)'},
    {id: 'wln', text: 'Walloon'},
    {id: 'wol', text: 'Wolof'},
    {id: 'xal', text: 'Oirat'},
    {id: 'xho', text: 'Xhosa'},
    {id: 'yao', text: 'Yao (Africa)'},
    {id: 'yap', text: 'Yapese'},
    {id: 'yid', text: 'Yiddish'},
    {id: 'yor', text: 'Yoruba'},
    {id: 'ypk', text: 'Yupik languages'},
    {id: 'zap', text: 'Zapotec'},
    {id: 'zbl', text: 'Blissymbolics'},
    {id: 'zen', text: 'Zenaga'},
    {id: 'zha', text: 'Zhuang'},
    {id: 'znd', text: 'Zande languages'},
    {id: 'zul', text: 'Zulu'},
    {id: 'zun', text: 'Zuni'},
    {id: 'zxx', text: 'No linguistic content'},
    {id: 'zza', text: 'Zaza'}
];
