let marcRealtorCodes = [
    {id: 'abr', text: 'Abridger'},
    {id: 'acp', text: 'Art copyist'},
    {id: 'act', text: 'Actor'},
    {id: 'adi', text: 'Art director'},
    {id: 'adp', text: 'Adapter'},
    {id: 'aft', text: 'Author of afterword, colophon, etc.'},
    {id: 'anl', text: 'Analyst'},
    {id: 'anm', text: 'Animator'},
    {id: 'ann', text: 'Annotator'},
    {id: 'ant', text: 'Bibliographic antecedent'},
    {id: 'ape', text: 'Appellee'},
    {id: 'apl', text: 'Appellant'},
    {id: 'app', text: 'Applicant'},
    {id: 'aqt', text: 'Author in quotations or text abstracts'},
    {id: 'arc', text: 'Architect'},
    {id: 'ard', text: 'Artistic director'},
    {id: 'arr', text: 'Arranger'},
    {id: 'art', text: 'Artist'},
    {id: 'asg', text: 'Assignee'},
    {id: 'asn', text: 'Associated name'},
    {id: 'ato', text: 'Autographer'},
    {id: 'att', text: 'Attributed name'},
    {id: 'auc', text: 'Auctioneer'},
    {id: 'aud', text: 'Author of dialog'},
    {id: 'aui', text: 'Author of introduction, etc.'},
    {id: 'aus', text: 'Screenwriter'},
    {id: 'aut', text: 'Author'},
    {id: 'bdd', text: 'Binding designer'},
    {id: 'bjd', text: 'Bookjacket designer'},
    {id: 'bkd', text: 'Book designer'},
    {id: 'bkp', text: 'Book producer'},
    {id: 'blw', text: 'Blurb writer'},
    {id: 'bnd', text: 'Binder'},
    {id: 'bpd', text: 'Bookplate designer'},
    {id: 'brd', text: 'Broadcaster'},
    {id: 'brl', text: 'Braille embosser'},
    {id: 'bsl', text: 'Bookseller'},
    {id: 'cas', text: 'Caster'},
    {id: 'ccp', text: 'Conceptor'},
    {id: 'chr', text: 'Choreographer'},
    {id: '-clb', text: 'Collaborator'},
    {id: 'cli', text: 'Client'},
    {id: 'cll', text: 'Calligrapher'},
    {id: 'clr', text: 'Colorist'},
    {id: 'clt', text: 'Collotyper'},
    {id: 'cmm', text: 'Commentator'},
    {id: 'cmp', text: 'Composer'},
    {id: 'cmt', text: 'Compositor'},
    {id: 'cnd', text: 'Conductor'},
    {id: 'cng', text: 'Cinematographer'},
    {id: 'cns', text: 'Censor'},
    {id: 'coe', text: 'Contestant-appellee'},
    {id: 'col', text: 'Collector'},
    {id: 'com', text: 'Compiler'},
    {id: 'con', text: 'Conservator'},
    {id: 'cor', text: 'Collection registrar'},
    {id: 'cos', text: 'Contestant'},
    {id: 'cot', text: 'Contestant-appellant'},
    {id: 'cou', text: 'Court governed'},
    {id: 'cov', text: 'Cover designer'},
    {id: 'cpc', text: 'Copyright claimant'},
    {id: 'cpe', text: 'Complainant-appellee'},
    {id: 'cph', text: 'Copyright holder'},
    {id: 'cpl', text: 'Complainant'},
    {id: 'cpt', text: 'Complainant-appellant'},
    {id: 'cre', text: 'Creator'},
    {id: 'crp', text: 'Correspondent'},
    {id: 'crr', text: 'Corrector'},
    {id: 'crt', text: 'Court reporter'},
    {id: 'csl', text: 'Consultant'},
    {id: 'csp', text: 'Consultant to a project'},
    {id: 'cst', text: 'Costume designer'},
    {id: 'ctb', text: 'Contributor'},
    {id: 'cte', text: 'Contestee-appellee'},
    {id: 'ctg', text: 'Cartographer'},
    {id: 'ctr', text: 'Contractor'},
    {id: 'cts', text: 'Contestee'},
    {id: 'ctt', text: 'Contestee-appellant'},
    {id: 'cur', text: 'Curator'},
    {id: 'cwt', text: 'Commentator for written text'},
    {id: 'dbp', text: 'Distribution place'},
    {id: 'dfd', text: 'Defendant'},
    {id: 'dfe', text: 'Defendant-appellee'},
    {id: 'dft', text: 'Defendant-appellant'},
    {id: 'dgg', text: 'Degree granting institution'},
    {id: 'dgs', text: 'Degree supervisor'},
    {id: 'dis', text: 'Dissertant'},
    {id: 'dln', text: 'Delineator'},
    {id: 'dnc', text: 'Dancer'},
    {id: 'dnr', text: 'Donor'},
    {id: 'dpc', text: 'Depicted'},
    {id: 'dpt', text: 'Depositor'},
    {id: 'drm', text: 'Draftsman'},
    {id: 'drt', text: 'Director'},
    {id: 'dsr', text: 'Designer'},
    {id: 'dst', text: 'Distributor'},
    {id: 'dtc', text: 'Data contributor'},
    {id: 'dte', text: 'Dedicatee'},
    {id: 'dtm', text: 'Data manager'},
    {id: 'dto', text: 'Dedicator'},
    {id: 'dub', text: 'Dubious author'},
    {id: 'edc', text: 'Editor of compilation'},
    {id: 'edm', text: 'Editor of moving image work'},
    {id: 'edt', text: 'Editor'},
    {id: 'egr', text: 'Engraver'},
    {id: 'elg', text: 'Electrician'},
    {id: 'elt', text: 'Electrotyper'},
    {id: 'eng', text: 'Engineer'},
    {id: 'enj', text: 'Enacting jurisdiction'},
    {id: 'etr', text: 'Etcher'},
    {id: 'evp', text: 'Event place'},
    {id: 'exp', text: 'Expert'},
    {id: 'fac', text: 'Facsimilist'},
    {id: 'fds', text: 'Film distributor'},
    {id: 'fld', text: 'Field director'},
    {id: 'flm', text: 'Film editor'},
    {id: 'fmd', text: 'Film director'},
    {id: 'fmk', text: 'Filmmaker'},
    {id: 'fmo', text: 'Former owner'},
    {id: 'fmp', text: 'Film producer'},
    {id: 'fnd', text: 'Funder'},
    {id: 'fpy', text: 'First party'},
    {id: 'frg', text: 'Forger'},
    {id: 'gis', text: 'Geographic information specialist'},
    {id: 'grt', text: 'Graphic technician'},
    {id: 'his', text: 'Host institution'},
    {id: 'hnr', text: 'Honoree'},
    {id: 'hst', text: 'Host'},
    {id: 'ill', text: 'Illustrator'},
    {id: 'ilu', text: 'Illuminator'},
    {id: 'ins', text: 'Inscriber'},
    {id: 'inv', text: 'Inventor'},
    {id: 'isb', text: 'Issuing body'},
    {id: 'itr', text: 'Instrumentalist'},
    {id: 'ive', text: 'Interviewee'},
    {id: 'ivr', text: 'Interviewer'},
    {id: 'jud', text: 'Judge'},
    {id: 'jug', text: 'Jurisdiction governed'},
    {id: 'lbr', text: 'Laboratory'},
    {id: 'lbt', text: 'Librettist'},
    {id: 'ldr', text: 'Laboratory director'},
    {id: 'led', text: 'Lead'},
    {id: 'lee', text: 'Libelee-appellee'},
    {id: 'lel', text: 'Libelee'},
    {id: 'len', text: 'Lender'},
    {id: 'let', text: 'Libelee-appellant'},
    {id: 'lgd', text: 'Lighting designer'},
    {id: 'lie', text: 'Libelant-appellee'},
    {id: 'lil', text: 'Libelant'},
    {id: 'lit', text: 'Libelant-appellant'},
    {id: 'lsa', text: 'Landscape architect'},
    {id: 'lse', text: 'Licensee'},
    {id: 'lso', text: 'Licensor'},
    {id: 'ltg', text: 'Lithographer'},
    {id: 'lyr', text: 'Lyricist'},
    {id: 'mcp', text: 'Music copyist'},
    {id: 'mdc', text: 'Metadata contact'},
    {id: 'med', text: 'Medium'},
    {id: 'mfp', text: 'Manufacture place'},
    {id: 'mfr', text: 'Manufacturer'},
    {id: 'mod', text: 'Moderator'},
    {id: 'mon', text: 'Monitor'},
    {id: 'mrb', text: 'Marbler'},
    {id: 'mrk', text: 'Markup editor'},
    {id: 'msd', text: 'Musical director'},
    {id: 'mte', text: 'Metal-engraver'},
    {id: 'mtk', text: 'Minute taker'},
    {id: 'mus', text: 'Musician'},
    {id: 'nrt', text: 'Narrator'},
    {id: 'opn', text: 'Opponent'},
    {id: 'org', text: 'Originator'},
    {id: 'orm', text: 'Organizer'},
    {id: 'osp', text: 'Onscreen presenter'},
    {id: 'oth', text: 'Other'},
    {id: 'own', text: 'Owner'},
    {id: 'pan', text: 'Panelist'},
    {id: 'pat', text: 'Patron'},
    {id: 'pbd', text: 'Publishing director'},
    {id: 'pbl', text: 'Publisher'},
    {id: 'pdr', text: 'Project director'},
    {id: 'pfr', text: 'Proofreader'},
    {id: 'pht', text: 'Photographer'},
    {id: 'plt', text: 'Platemaker'},
    {id: 'pma', text: 'Permitting agency'},
    {id: 'pmn', text: 'Production manager'},
    {id: 'pop', text: 'Printer of plates'},
    {id: 'ppm', text: 'Papermaker'},
    {id: 'ppt', text: 'Puppeteer'},
    {id: 'pra', text: 'Praeses'},
    {id: 'prc', text: 'Process contact'},
    {id: 'prd', text: 'Production personnel'},
    {id: 'pre', text: 'Presenter'},
    {id: 'prf', text: 'Performer'},
    {id: 'prg', text: 'Programmer'},
    {id: 'prm', text: 'Printmaker'},
    {id: 'prn', text: 'Production company'},
    {id: 'pro', text: 'Producer'},
    {id: 'prp', text: 'Production place'},
    {id: 'prs', text: 'Production designer'},
    {id: 'prt', text: 'Printer'},
    {id: 'prv', text: 'Provider'},
    {id: 'pta', text: 'Patent applicant'},
    {id: 'pte', text: 'Plaintiff-appellee'},
    {id: 'ptf', text: 'Plaintiff'},
    {id: 'pth', text: 'Patent holder'},
    {id: 'ptt', text: 'Plaintiff-appellant'},
    {id: 'pup', text: 'Publication place'},
    {id: 'rbr', text: 'Rubricator'},
    {id: 'rcd', text: 'Recordist'},
    {id: 'rce', text: 'Recording engineer'},
    {id: 'rcp', text: 'Addressee'},
    {id: 'rdd', text: 'Radio director'},
    {id: 'red', text: 'Redaktor'},
    {id: 'ren', text: 'Renderer'},
    {id: 'res', text: 'Researcher'},
    {id: 'rev', text: 'Reviewer'},
    {id: 'rpc', text: 'Radio producer'},
    {id: 'rps', text: 'Repository'},
    {id: 'rpt', text: 'Reporter'},
    {id: 'rpy', text: 'Responsible party'},
    {id: 'rse', text: 'Respondent-appellee'},
    {id: 'rsg', text: 'Restager'},
    {id: 'rsp', text: 'Respondent'},
    {id: 'rsr', text: 'Restorationist'},
    {id: 'rst', text: 'Respondent-appellant'},
    {id: 'rth', text: 'Research team head'},
    {id: 'rtm', text: 'Research team member'},
    {id: 'sad', text: 'Scientific advisor'},
    {id: 'sce', text: 'Scenarist'},
    {id: 'scl', text: 'Sculptor'},
    {id: 'scr', text: 'Scribe'},
    {id: 'sds', text: 'Sound designer'},
    {id: 'sec', text: 'Secretary'},
    {id: 'sgd', text: 'Stage director'},
    {id: 'sgn', text: 'Signer'},
    {id: 'sht', text: 'Supporting host'},
    {id: 'sll', text: 'Seller'},
    {id: 'sng', text: 'Singer'},
    {id: 'spk', text: 'Speaker'},
    {id: 'spn', text: 'Sponsor'},
    {id: 'spy', text: 'Second party'},
    {id: 'srv', text: 'Surveyor'},
    {id: 'std', text: 'Set designer'},
    {id: 'stg', text: 'Setting'},
    {id: 'stl', text: 'Storyteller'},
    {id: 'stm', text: 'Stage manager'},
    {id: 'stn', text: 'Standards body'},
    {id: 'str', text: 'Stereotyper'},
    {id: 'tcd', text: 'Technical director'},
    {id: 'tch', text: 'Teacher'},
    {id: 'ths', text: 'Thesis advisor'},
    {id: 'tld', text: 'Television director'},
    {id: 'tlp', text: 'Television producer'},
    {id: 'trc', text: 'Transcriber'},
    {id: 'trl', text: 'Translator'},
    {id: 'tyd', text: 'Type designer'},
    {id: 'tyg', text: 'Typographer'},
    {id: 'uvp', text: 'University place'},
    {id: 'vac', text: 'Voice actor'},
    {id: 'vdg', text: 'Videographer'},
    {id: '-voc', text: 'Vocalist'},
    {id: 'wac', text: 'Writer of added commentary'},
    {id: 'wal', text: 'Writer of added lyrics'},
    {id: 'wam', text: 'Writer of accompanying material'},
    {id: 'wat', text: 'Writer of added text'},
    {id: 'wdc', text: 'Woodcutter'},
    {id: 'wde', text: 'Wood engraver'},
    {id: 'win', text: 'Writer of introduction'},
    {id: 'wit', text: 'Witness'},
    {id: 'wpr', text: 'Writer of preface'},
    {id: 'wst', text: 'Writer of supplementary textual content'}
]